# database/routes_data.py

ROUTES = {
    1: {
        "name_ru": "🏛️ За кулисами советской истории",
        "name_en": "🏛️ Behind the Scenes of Soviet History",
        "points": 5,
        "distance_ru": "4.2 км",
        "distance_en": "4.2 km",
        "time_ru": "1.5-2 часа",
        "time_en": "1.5-2 hours",
        "district_ru": "Сокол, Динамо",
        "district_en": "Sokol, Dynamo",
        "theme_ru": "Советская архитектура, элитное жилье",
        "theme_en": "Soviet architecture, elite housing",
        "description_ru": "Маршрут по знаковым местам советской эпохи: от сталинских высоток до экспериментального жилья.",
        "description_en": "A route through iconic Soviet sites: from Stalinist skyscrapers to experimental housing."
    },
    2: {
        "name_ru": "🌳 От царской охоты к парку",
        "name_en": "🌳 From Royal Hunt to the Park",
        "points": 5,
        "distance_ru": "3.8 км",
        "distance_en": "3.8 km",
        "time_ru": "1.5 часа",
        "time_en": "1.5 hours",
        "district_ru": "Сокольники, Преображенское",
        "district_en": "Sokolniki, Preobrazhenskoe",
        "theme_ru": "Исторические парки, конструктивизм",
        "theme_en": "Historical parks, constructivism",
        "description_ru": "Прогулка от старейшего парка Москвы через памятники конструктивизма к промышленной архитектуре.",
        "description_en": "A walk from Moscow's oldest park through constructivist monuments to industrial architecture."
    },
    3: {
        "name_ru": "🏘️ Непарадное Замоскворечье",
        "name_en": "🏘️ Non-festive Zamoskvorechye",
        "points": 6,
        "distance_ru": "3.5 км",
        "distance_en": "3.5 km",
        "time_ru": "2 часа",
        "time_en": "2 hours",
        "district_ru": "Замоскворечье, Пятницкая",
        "district_en": "Zamoskvorechye, Pyatnitskaya",
        "theme_ru": "Старообрядческие храмы, промышленная история",
        "theme_en": "Old Believer churches, industrial history",
        "description_ru": "Маршрут по тихим переулкам Замоскворечья с его храмами, купеческими особняками и фабриками.",
        "description_en": "A route through the quiet alleys of Zamoskvorechye with its churches, merchant mansions, and factories."
    },
    4: {
        "name_ru": "🎨 Московский модерн Шехтеля",
        "name_en": "🎨 Shekhtel's Moscow Art Nouveau",
        "points": 6,
        "distance_ru": "4.5 км",
        "distance_en": "4.5 km",
        "time_ru": "2-2.5 часа",
        "time_en": "2-2.5 hours",
        "district_ru": "Арбат, Остоженка",
        "district_en": "Arbat, Ostozhenka",
        "theme_ru": "Архитектура модерна, особняки купцов",
        "theme_en": "Art Nouveau architecture, merchant mansions",
        "description_ru": "Путь по самым известным зданиям московского модерна, созданным гением Фёдора Шехтеля.",
        "description_en": "A journey through the most famous Moscow Art Nouveau buildings created by the genius Fyodor Shekhtel."
    },
    5: {
        "name_ru": "🚀 ВДНХ: От павильонов к космосу",
        "name_en": "🚀 VDNKH: From Pavilions to Space",
        "points": 7,
        "distance_ru": "5.2 км",
        "distance_en": "5.2 km",
        "time_ru": "2.5-3 часа",
        "time_en": "2.5-3 hours",
        "district_ru": "ВДНХ, Останкино",
        "district_en": "VDNKH, Ostankino",
        "theme_ru": "Советская архитектура, космос",
        "theme_en": "Soviet architecture, space",
        "description_ru": "Маршрут от знаменитых павильонов ВДНХ через Останкинскую башню к музею космонавтики.",
        "description_en": "A route from the famous VDNKH pavilions through the Ostankino Tower to the Museum of Cosmonautics."
    },
    6: {
        "name_ru": "📚 Поэтический Арбат",
        "name_en": "📚 Poetic Arbat",
        "points": 8,
        "distance_ru": "2.8 км",
        "distance_en": "2.8 km",
        "time_ru": "2 часа",
        "time_en": "2 hours",
        "district_ru": "Арбат и переулки",
        "district_en": "Arbat and alleys",
        "theme_ru": "Литературные музеи, история театров",
        "theme_en": "Literary museums, history of theaters",
        "description_ru": "Литературное путешествие по Арбату и его переулкам, связанным с великими писателями и поэтами.",
        "description_en": "A literary journey through Arbat and its alleys associated with great writers and poets."
    },
    7: {
        "name_ru": "🏭 Промышленный авангард",
        "name_en": "🏭 Industrial Avant-garde",
        "points": 7,
        "distance_ru": "6.1 км",
        "distance_en": "6.1 km",
        "time_ru": "3 часа",
        "time_en": "3 hours",
        "district_ru": "ЗИЛ, Красный Октябрь",
        "district_en": "ZIL, Krasny Oktyabr",
        "theme_ru": "Бывшие фабрики, арт-кластеры",
        "theme_en": "Former factories, art clusters",
        "description_ru": "Исследование промышленной архитектуры Москвы, превратившейся в центры искусства и культуры.",
        "description_en": "Exploring Moscow's industrial architecture transformed into centers of art and culture."
    },
    8: {
        "name_ru": "🕵️ Тайны Хитровки",
        "name_en": "🕵️ Secrets of Khitrovka",
        "points": 7,
        "distance_ru": "3.2 км",
        "distance_en": "3.2 km",
        "time_ru": "2 часа",
        "time_en": "2 hours",
        "district_ru": "Хитровка, Ивановская горка",
        "district_en": "Khitrovka, Ivanovskaya Gorka",
        "theme_ru": "Исторические палаты, монастыри",
        "theme_en": "Historical chambers, monasteries",
        "description_ru": "Маршрут по одному из самых древних районов Москвы с его храмами, палатами и легендами.",
        "description_en": "A route through one of Moscow's most ancient districts with its temples, chambers, and legends."
    },
    9: {
        "name_ru": "🏡 Дачная жизнь прошлого",
        "name_en": "🏡 Country Life of the Past",
        "points": 7,
        "distance_ru": "12.5 км (на транспорте)",
        "distance_en": "12.5 km (by transport)",
        "time_ru": "4-5 часов",
        "time_en": "4-5 hours",
        "district_ru": "Люблино, Кузьминки, Коломенское",
        "district_en": "Lyublino, Kuzminki, Kolomenskoye",
        "theme_ru": "Усадьбы, парки, дачная архитектура",
        "theme_en": "Estates, parks, dacha architecture",
        "description_ru": "Путешествие по южным усадьбам Москвы, от роскошных дворцов до скромных дач.",
        "description_en": "A journey through Moscow's southern estates, from luxurious palaces to modest dachas."
    },
    10: {
        "name_ru": "🔬 Научный городок",
        "name_en": "🔬 Science Town",
        "points": 8,
        "distance_ru": "4.8 км",
        "distance_en": "4.8 km",
        "time_ru": "2.5 часа",
        "time_en": "2.5 hours",
        "district_ru": "Воробьевы горы, Ленинские горы",
        "district_en": "Vorobyovy Gory, Leninskiye Gory",
        "theme_ru": "Университеты, научные центры",
        "theme_en": "Universities, scientific centers",
        "description_ru": "Маршрут по научной Москве: от МГУ через институты Академии наук к современным исследовательским центрам.",
        "description_en": "A route through scientific Moscow: from MSU through the Academy of Sciences institutes to modern research centers."
    }
}

MAP_URL = "https://gerasimovaleksei.github.io/Gid_eon/"